version: "3"
services:
    xhtml-formatter:
        container_name: xhtml-formatter
        working_dir: /var/www/html
        build: .
        volumes:
            - .:/var/www/html:delegated
        ports:
            - "83:83"
